language: cpp
cache: ccache
matrix:
  include:
    - os: linux
      env: NAME="linux appimage"
      sudo: required
      dist: focal
      services: docker
      git:
       clone: true
       submodules: false
      before_install:
       - sudo apt-get update
       - sudo apt-get -y install libsdl2-dev
       - sudo apt-cache policy libsdl2-dev
      addons:
        apt:
          packages:
            - p7zip-full
      install: 
       - docker pull quriouspixel/yuzu:latest
      script: 
       - mkdir -p "$HOME/.ccache"
       - docker run -u root -e ENABLE_COMPATIBILITY_REPORTING --env-file .travis/travis-ci.env -v $(pwd):/yuzu -v "$HOME/.ccache":/root/.ccache --name yuzu_appimage quriouspixel/yuzu:latest /bin/bash /yuzu/.travis/docker.sh
      after_success:
      - ls -al artifacts/
      - cd artifacts/
      - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
      - chmod a+x upload.sh
      - bash upload.sh yuzu* 
      branches:
  except:
    - /^(?i:continuous.*)$/
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
#  secure: 
  file_glob: true
  file: "artifacts/*"
  skip_cleanup: true
  on:
    tags: true
